name: Code Analysis

on:
    pull_request: null
    push:
        branches:
            - main

jobs:
    code_analysis:
        strategy:
            fail-fast: false
            matrix:
                actions:
                    -
                        name: "PHPStan"
                        run: vendor/bin/phpstan

                    -
                        name: "Composer Validate"
                        run: composer validate --ansi

                    -
                        name: "PHPUnit"
                        run: vendor/bin/phpunit --exclude-group shouldFail,wip

                    -
                        name: "Rector"
                        run: vendor/bin/rector --ansi

                    -
                        name: "Coding Standards"
                        run: vendor/bin/ecs check --ansi

        name: ${{ matrix.actions.name }}
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            # see https://github.com/shivammathur/setup-php
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.2
                    coverage: none

            # composer install cache - https://github.com/ramsey/composer-install
            -   uses: "ramsey/composer-install@v1"

            -   run: ${{ matrix.actions.run }}
